@baseUrl = http://localhost:3333

### Get all users
# @name create_user
POST {{baseUrl}}/user
Content-Type: application/json

{
    "name": "John Doe",
    "email": 2,
    "password": "password123"
}

###
